const url = "https://script.google.com/macros/s/AKfycbyg9RmH2iFblNzWNBBL7J4SR-W003CQnDju8RPoPBINF_cD6Fdidkn7h9QLvMsL8u4z/exec";
const whatsappNumber = "917593925926"; // അന്താരാഷ്ട്ര ഫോർമാറ്റിൽ ഉള്ള നിങ്ങളുടെ നമ്പർ

let productList = [];
let cart = [];

document.getElementById("products").innerHTML = "Loading products...";

// ഗൂഗിൾ ഷീറ്റിൽ നിന്നും ഡാറ്റ എടുക്കുന്നു
fetch(url)
  .then(response => response.json())
    .then(data => {
        productList = Array.isArray(data) ? data : (data.data || []);
            displayProducts();
              })
                .catch(error => {
                    console.error("Error:", error);
                        document.getElementById("products").innerHTML = "<h2>Data Load Failed</h2>";
                          });

                          // പ്രൊഡക്റ്റുകൾ സ്ക്രീനിൽ കാണിക്കുന്നു
                          function displayProducts() {
                            let html = "";
                              
                                if (productList.length === 0) {
                                    document.getElementById("products").innerHTML = "<p>No products available</p>";
                                        return;
                                          }

                                            productList.forEach((item, index) => {
                                                // കോളങ്ങളുടെ പേര് ക്രമീകരിക്കുന്നു
                                                    const keys = Object.keys(item).reduce((acc, key) => {
                                                          acc[key.toLowerCase().replace(/\s+/g, '')] = item[key];
                                                                return acc;
                                                                    }, {});

                                                                        let name = keys['name'] || "No Name";
                                                                            let regPrice = parseFloat(keys['regularprice']) || 0;
                                                                                let offPrice = parseFloat(keys['offerprice']) || 0;

                                                                                    if (name !== "No Name" && offPrice > 0) {
                                                                                          html += `
                                                                                                  <div class="product">
                                                                                                            <h3>${name}</h3>
                                                                                                                      <div class="price-info">
                                                                                                                                  <span class="reg-price">₹${regPrice} / kg</span>
                                                                                                                                              <span class="off-price">₹${offPrice} / kg</span>
                                                                                                                                                        </div>
                                                                                                                                                                  <div class="controls">
                                                                                                                                                                              <select id="weight-${index}">
                                                                                                                                                                                            <option value="0.25">250 g</option>
                                                                                                                                                                                                          <option value="0.5">500 g</option>
                                                                                                                                                                                                                        <option value="1" selected>1 kg</option>
                                                                                                                                                                                                                                      <option value="2">2 kg</option>
                                                                                                                                                                                                                                                    <option value="5">5 kg</option>
                                                                                                                                                                                                                                                                  <option value="10">10 kg</option>
                                                                                                                                                                                                                                                                                <option value="25">25 kg</option>
                                                                                                                                                                                                                                                                                              <option value="50">50 kg</option>
                                                                                                                                                                                                                                                                                                            <option value="100">100 kg</option>
                                                                                                                                                                                                                                                                                                                        </select>
                                                                                                                                                                                                                                                                                                                                    <button class="add-btn" onclick="addToCart(${index}, '${name}', ${offPrice})">Add to Cart</button>
                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                            `;
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                    document.getElementById("products").innerHTML = html;
                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                    // കാർട്ടിലേക്ക് പച്ചക്കറി ആഡ് ചെയ്യുന്നു
                                                                                                                                                                                                                                                                                                                                                                    function addToCart(index, name, pricePerKg) {
                                                                                                                                                                                                                                                                                                                                                                      const weightSelect = document.getElementById(`weight-${index}`);
                                                                                                                                                                                                                                                                                                                                                                        const selectedWeight = parseFloat(weightSelect.value);
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                            // തിരഞ്ഞെടുക്കുന്ന അളവിനനുസരിച്ചുള്ള വില കണക്കാക്കുന്നു
                                                                                                                                                                                                                                                                                                                                                                              const itemPrice = pricePerKg * selectedWeight;
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                  // തൂക്കം ടെക്സ്റ്റ് രൂപത്തിലാക്കാൻ (ഉദാഹരണത്തിന്: 250g അല്ലെങ്കിൽ 2kg)
                                                                                                                                                                                                                                                                                                                                                                                    let weightText = selectedWeight < 1 ? (selectedWeight * 1000) + "g" : selectedWeight + "kg";

                                                                                                                                                                                                                                                                                                                                                                                      // ഒരേ സാധനം വീണ്ടും ആഡ് ചെയ്താൽ ലിസ്റ്റിൽ പുതുക്കുന്നു
                                                                                                                                                                                                                                                                                                                                                                                        const existingItemIndex = cart.findIndex(item => item.name === name && item.weightText === weightText);
                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                            if (existingItemIndex > -1) {
                                                                                                                                                                                                                                                                                                                                                                                                alert(`${name} (${weightText}) already in cart!`);
                                                                                                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                                                                                                                                          cart.push({
                                                                                                                                                                                                                                                                                                                                                                                                                name: name,
                                                                                                                                                                                                                                                                                                                                                                                                                      weight: selectedWeight,
                                                                                                                                                                                                                                                                                                                                                                                                                            weightText: weightText,
                                                                                                                                                                                                                                                                                                                                                                                                                                  price: itemPrice
                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                          updateCartUI();
                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                          // കാർട്ട് വിവരങ്ങൾ സ്ക്രീനിൽ പുതുക്കുന്നു
                                                                                                                                                                                                                                                                                                                                                                                                                                          function updateCartUI() {
                                                                                                                                                                                                                                                                                                                                                                                                                                            const cartItemsDiv = document.getElementById("cart-items");
                                                                                                                                                                                                                                                                                                                                                                                                                                              const cartTotalDiv = document.getElementById("cart-total");

                                                                                                                                                                                                                                                                                                                                                                                                                                                if (cart.length === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    cartItemsDiv.innerHTML = "Cart Empty";
                                                                                                                                                                                                                                                                                                                                                                                                                                                        cartTotalDiv.innerHTML = "Total: ₹0";
                                                                                                                                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                let html = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  let total = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cart.forEach((item, index) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        html += `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="cart-item">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span>${item.name} (${item.weightText}) - ₹${item.price.toFixed(2)}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span class="remove-btn" onclick="removeFromCart(${index})">❌</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            total += item.price;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cartItemsDiv.innerHTML = html;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cartTotalDiv.innerHTML = `Total: ₹${total.toFixed(2)}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // കാർട്ടിൽ നിന്ന് ഒഴിവാക്കാൻ
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  function removeFromCart(index) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cart.splice(index, 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      updateCartUI();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // വാട്സാപ്പിലേക്ക് ഓർഡർ അയക്കുന്നു
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      function sendWhatsAppOrder() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const name = document.getElementById("cust-name").value.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const phone = document.getElementById("cust-phone").value.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const address = document.getElementById("cust-address").value.trim();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (cart.length === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  alert("Your cart is empty!");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!name || !phone || !address) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              alert("Please fill in your Name, Phone Number, and Address.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // വാട്സാപ്പ് മെസ്സേജ് ഫോർമാറ്റ് ചെയ്യുന്നു
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let message = `*New Vegetable Order From NSI VEGETABLES*\n\n`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          message += `*Customer Details:*\n`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            message += `Name: ${name}\n`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              message += `Phone: ${phone}\n`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                message += `Address: ${address}\n\n`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  message += `*Ordered Items:*\n`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let grandTotal = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      cart.forEach((item, index) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          message += `${index + 1}. ${item.name} (${item.weightText}) - ₹${item.price.toFixed(2)}\n`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              grandTotal += item.price;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  message += `\n*Grand Total: ₹${grandTotal.toFixed(2)}*`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // വാട്സാപ്പ് ലിങ്ക് നിർമ്മിച്ച് അങ്ങോട്ട് റീഡയറക്ട് ചെയ്യുന്നു
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const encodedMessage = encodeURIComponent(message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const whatsappUrl = `https://api.whatsapp.com/send?phone=${whatsappNumber}&text=${encodedMessage}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            window.open(whatsappUrl, '_blank');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            