// പഴയ url മാറ്റിയ ശേഷം ഇത് പേസ്റ്റ് ചെയ്യുക
const baseUrl = "https://script.google.com/macros/s/AKfycbyg9RmH2iFblNzWNBBL7J4SR-W003CQnDju8RPoPBINF_cD6Fdidkn7h9QLvMsL8u4z/exec";
const url = `${baseUrl}?_=${new Date().getTime()}`;

const whatsappNumber = "917593925926";

let productList = [];
let cart = {};

document.getElementById("products").innerHTML = "Loading products...";

// ഗൂഗിൾ ഷീറ്റിൽ നിന്നും ഡാറ്റ എടുക്കുന്നു
fetch(url)
  .then(response => response.json())
    .then(data => {
        productList = Array.isArray(data) ? data : (data.data || []);
            displayProducts();
              })
                .catch(error => {
                    console.error("Error:", error);
                        document.getElementById("products").innerHTML = "<p>Data Load Failed</p>";
                          });

                          function displayProducts() {
                            let html = "";
                              
                                if (productList.length === 0) {
                                    document.getElementById("products").innerHTML = "<p>No products available</p>";
                                        return;
                                          }

                                            productList.forEach((item, index) => {
                                                const keys = Object.keys(item).reduce((acc, key) => {
                                                      acc[key.toLowerCase().replace(/\s+/g, '')] = item[key];
                                                            return acc;
                                                                }, {});

                                                                    let name = keys['name'] || "No Name";
                                                                        let offPrice = parseFloat(keys['offerprice']) || 0;

                                                                            if (name !== "No Name" && offPrice > 0) {
                                                                                  const itemKey = `prod_${index}`;
                                                                                        
                                                                                              html += `
                                                                                                      <div class="product">
                                                                                                                <div class="product-details">
                                                                                                                            <p class="product-name">${name}</p>
                                                                                                                                        <p class="product-price">₹${offPrice}/kg</p>
                                                                                                                                                  </div>
                                                                                                                                                            <div class="qty-controls">
                                                                                                                                                                        <button class="btn-minus" onclick="changeQty('${itemKey}', '${name}', ${offPrice}, -0.25)">-</button>
                                                                                                                                                                                    <span class="qty-value" id="qty-${itemKey}">0</span>
                                                                                                                                                                                                <button class="btn-plus" onclick="changeQty('${itemKey}', '${name}', ${offPrice}, 0.25)">+</button>
                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                        `;
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                document.getElementById("products").innerHTML = html;
                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                // 250g (0.25 kg) വീതം കൂട്ടാനും കുറയ്ക്കാനും ഉള്ള ഫങ്ക്ഷൻ
                                                                                                                                                                                                                                function changeQty(key, name, pricePerKg, change) {
                                                                                                                                                                                                                                  if (!cart[key]) {
                                                                                                                                                                                                                                      cart[key] = { name: name, price: pricePerKg, qty: 0 };
                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                          cart[key].qty += change;

                                                                                                                                                                                                                                            // അളവ് 0-ൽ കുറയാൻ പാടില്ല
                                                                                                                                                                                                                                              if (cart[key].qty < 0) {
                                                                                                                                                                                                                                                  cart[key].qty = 0;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                        // മാക്സിമം കപ്പാസിറ്റി 100kg ആയി പരിമിതപ്പെടുത്തുന്നു
                                                                                                                                                                                                                                                          if (cart[key].qty > 100) {
                                                                                                                                                                                                                                                              cart[key].qty = 100;
                                                                                                                                                                                                                                                                  alert("Maximum order capacity is 100kg");
                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                      const currentQty = cart[key].qty;

                                                                                                                                                                                                                                                                        // വെബ്‌സൈറ്റ് ഡിസ്‌പ്ലേയിൽ ഭംഗിയായി കാണിക്കാൻ (ഉദാ: 250g, 1kg, 1kg 250g)
                                                                                                                                                                                                                                                                          let displayText = formatWeight(currentQty);
                                                                                                                                                                                                                                                                            document.getElementById(`qty-${key}`).innerText = displayText;

                                                                                                                                                                                                                                                                              // അളവ് പൂജ്യമായാൽ കാർട്ടിൽ നിന്ന് നീക്കുക
                                                                                                                                                                                                                                                                                if (currentQty === 0) {
                                                                                                                                                                                                                                                                                    delete cart[key];
                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                        updateCartUI();
                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                        // കിലോഗ്രാമിനെ കസ്റ്റമർക്ക് മനസ്സിലാകുന്ന രീതിയിലേക്ക് മാറ്റുന്ന ഫങ്ക്ഷൻ
                                                                                                                                                                                                                                                                                        function formatWeight(kg) {
                                                                                                                                                                                                                                                                                          if (kg === 0) return "0";
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                              let totalGrams = kg * 1000;
                                                                                                                                                                                                                                                                                                let kilograms = Math.floor(totalGrams / 1000);
                                                                                                                                                                                                                                                                                                  let grams = totalGrams % 1000;

                                                                                                                                                                                                                                                                                                    if (kilograms > 0 && grams > 0) {
                                                                                                                                                                                                                                                                                                        return `${kilograms}kg ${grams}g`;
                                                                                                                                                                                                                                                                                                          } else if (kilograms > 0) {
                                                                                                                                                                                                                                                                                                              return `${kilograms}kg`;
                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                    return `${grams}g`;
                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                      // കാർട്ട് വിവരങ്ങൾ പുതുക്കുന്നു
                                                                                                                                                                                                                                                                                                                      function updateCartUI() {
                                                                                                                                                                                                                                                                                                                        const cartItemsDiv = document.getElementById("cart-items");
                                                                                                                                                                                                                                                                                                                          const cartTotalDiv = document.getElementById("cart-total");
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                              const activeKeys = Object.keys(cart);

                                                                                                                                                                                                                                                                                                                                if (activeKeys.length === 0) {
                                                                                                                                                                                                                                                                                                                                    cartItemsDiv.innerHTML = "Cart Empty";
                                                                                                                                                                                                                                                                                                                                        cartTotalDiv.innerHTML = "Total ₹0";
                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                let html = "";
                                                                                                                                                                                                                                                                                                                                                  let total = 0;

                                                                                                                                                                                                                                                                                                                                                    activeKeys.forEach(key => {
                                                                                                                                                                                                                                                                                                                                                        const item = cart[key];
                                                                                                                                                                                                                                                                                                                                                            const itemTotal = item.price * item.qty;
                                                                                                                                                                                                                                                                                                                                                                total += itemTotal;
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                        html += `
                                                                                                                                                                                                                                                                                                                                                                              <div class="cart-item">
                                                                                                                                                                                                                                                                                                                                                                                      <span>${item.name} (${formatWeight(item.qty)})</span>
                                                                                                                                                                                                                                                                                                                                                                                              <span>₹${itemTotal.toFixed(2)}</span>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                        `;
                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                            cartItemsDiv.innerHTML = html;
                                                                                                                                                                                                                                                                                                                                                                                                              cartTotalDiv.innerHTML = `Total ₹${total.toFixed(2)}`;
                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                              // വാട്സാപ്പിലേക്ക് ഓർഡർ അയക്കുന്നു
                                                                                                                                                                                                                                                                                                                                                                                                              function sendWhatsAppOrder() {
                                                                                                                                                                                                                                                                                                                                                                                                                const name = document.getElementById("cust-name").value.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                  const phone = document.getElementById("cust-phone").value.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                    const address = document.getElementById("cust-address").value.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                        const activeKeys = Object.keys(cart);

                                                                                                                                                                                                                                                                                                                                                                                                                          if (activeKeys.length === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                              alert("Please add items to your cart first!");
                                                                                                                                                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!name || !phone || !address) {
                                                                                                                                                                                                                                                                                                                                                                                                                                          alert("Please fill Name, Phone, and Address.");
                                                                                                                                                                                                                                                                                                                                                                                                                                              return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                  let message = `*New Vegetable Order From NSI VEGETABLES*\n\n`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    message += `*Customer Details:*\n`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                      message += `Name: ${name}\n`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        message += `Phone: ${phone}\n`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                          message += `Address: ${address}\n\n`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            message += `*Items:*\n`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                              let grandTotal = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                activeKeys.forEach((key, index) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const item = cart[key];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const itemTotal = item.price * item.qty;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            grandTotal += itemTotal;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                message += `${index + 1}. ${item.name} - ${formatWeight(item.qty)} (₹${itemTotal.toFixed(2)})\n`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    message += `\n*Total: ₹${grandTotal.toFixed(2)}*`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const encodedMessage = encodeURIComponent(message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const whatsappUrl = `https://api.whatsapp.com/send?phone=${whatsappNumber}&text=${encodedMessage}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            window.open(whatsappUrl, '_blank');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            